export const DELETE_TASK = "DELETE_TASK" 

export const TASKBOARD_REQUEST = "TASKBOARD_REQUEST"

export const FETCH_REQUEST = "MOVETASK_REQUEST" 
export const FETCH_SUCCESS = "FETCH_SUCCESS"
export const MOVETASK_FAIL = "MOVETASK_FAIL"  